name: '[AU4] Check: Codestyle'

on:
  pull_request:
    branches:
    - master

jobs:
  au4_codestyle:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format-19
    - name: Check code style
      run: |
        ./buildscripts/ci/checkcodestyle/run_scan.sh
